
-- CONNECTED IN OWNER 'X' THAT HAS PRIVILEGES AND I WANT TO GIVE PRIVILEGES TO ALL TABLES FOR OWNER 'USER_WHO_NEEDS_PRIVILEGES'
BEGIN
  FOR REC IN (SELECT 'GRANT ALL PRIVILEGES ON ' || X.TABLE_NAME || ' TO USER_WHO_NEEDS_PRIVILEGES' SCRIPT FROM USER_TABLES X) 
  LOOP
    EXECUTE IMMEDIATE REC.SCRIPT;
  END LOOP;
END;
